# Generated by Django 4.2.5 on 2023-09-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourite',
            name='unique_userrecipes',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_usershopping',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_userrecipes'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_usershopping'),
        ),
    ]
