### Получаем список пользователей

GET http://127.0.0.1:8000/api/users/
content-type: application/json
Authorization: 
{
    "auth_token": "9e614322ae8146ee6c09e18baf3400ae4824c3cb"
}

###Регистрация пользователя 1

POST http://127.0.0.1:8000/api/users/
content-type: application/json

{
    "username": "OlegP",
    "email": "test1@yandex.ru",    
    "first_name": "Олег",
    "last_name": "Прибыткин",
    "password": "123Qwe456rty"
}

###Регистрация пользователя 2

POST http://127.0.0.1:8000/api/users/
content-type: application/json

{
    "username": "SvetaV",
    "email": "test2@yandex.ru",    
    "first_name": "Света",
    "last_name": "Валиулова",
    "password": "123Qwe456rty"
}

### Просмотр профиля пользователя

GET http://127.0.0.1:8000/api/users/2/

###

GET http://127.0.0.1:8000/api/users/1/

### Просмотр текущего пользователя

GET http://127.0.0.1:8000/api/users/me/

###Изменение пароля

POST http://127.0.0.1:8000/api/users/set_password/
content-type: application/json

{
    "new_password": "123Qwe456rty",
    "current_password": "123Qwe456rty"
}

### Получение токена авторизации пользователя 1
POST http://127.0.0.1:8000/api/auth/token/login/
content-type: application/json

{
    "password": "123Qwe456rty",
    "email": "test1@yandex.ru"

}

### Получение токена авторизации пользователя 2
POST http://127.0.0.1:8000/api/auth/token/login/
content-type: application/json

{
    "password": "123Qwe456rty",
    "email": "test2@yandex.ru"

}

### Получение токена авторизации супер пользователя
POST http://127.0.0.1:8000/api/auth/token/login/
content-type: application/json

{
    "password": "123456qwerty",
    "email": "ov.reatch@gmail.com"

}
### Удаление токена текущего пользователя
POST http://127.0.0.1:8000/api/auth/token/logout/


### Мои подписки

GET http://127.0.0.1:8000/api/users/subscriptions/
### Подписаться на пользователя

