# Generated by Django 4.2.5 on 2023-11-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipes',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
