# Generated by Django 4.2.5 on 2023-11-05 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipes',
            name='amount',
            field=models.PositiveSmallIntegerField(error_messages={'validators': 'Количество ингридиентов неверно.'}, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
