# Generated by Django 4.2.5 on 2023-11-04 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredientrecipes_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipes',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингредиентов 1.')]),
        ),
    ]
