# Generated by Django 4.2.5 on 2023-11-04 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredientrecipes_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipes',
            name='amount',
            field=models.IntegerField(error_messages={'ingredients': 'Минимальное количество ингредиентов 1.'}, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
